"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubCategory_Language = exports.SubCategory_Military = exports.SubCategory_Medical = exports.SubCategory_Law = exports.SubCategory_CourseSubjects = exports.SubCategory_Technology = exports.Category = void 0;
exports.makeCardSet = makeCardSet;
function makeCardSet(ownerID, setName, category, subCategory, description, setID) {
    return { ownerID, setName, category, subCategory, description, setID };
}
var Category;
(function (Category) {
    Category[Category["Language"] = 0] = "Language";
    Category[Category["Technology"] = 1] = "Technology";
    Category[Category["CourseSubjects"] = 2] = "CourseSubjects";
    Category[Category["Law"] = 3] = "Law";
    Category[Category["Medical"] = 4] = "Medical";
    Category[Category["Military"] = 5] = "Military";
})(Category || (exports.Category = Category = {}));
var SubCategory_Technology;
(function (SubCategory_Technology) {
    SubCategory_Technology["Programming"] = "Programming";
    SubCategory_Technology["Cybersecurity"] = "Cybersecurity";
    SubCategory_Technology["ArtificialIntelligence"] = "Artificial Intelligence";
    SubCategory_Technology["CloudComputing"] = "Cloud Computing";
    SubCategory_Technology["Networking"] = "Networking";
    SubCategory_Technology["Databases"] = "Databases";
    SubCategory_Technology["OperatingSystems"] = "Operating Systems";
    SubCategory_Technology["SoftwareDevelopment"] = "Software Development";
    SubCategory_Technology["Hardware"] = "Hardware";
    SubCategory_Technology["Blockchain"] = "Blockchain";
})(SubCategory_Technology || (exports.SubCategory_Technology = SubCategory_Technology = {}));
var SubCategory_CourseSubjects;
(function (SubCategory_CourseSubjects) {
    SubCategory_CourseSubjects["Mathematics"] = "Mathematics";
    SubCategory_CourseSubjects["Physics"] = "Physics";
    SubCategory_CourseSubjects["Chemistry"] = "Chemistry";
    SubCategory_CourseSubjects["Biology"] = "Biology";
    SubCategory_CourseSubjects["History"] = "History";
    SubCategory_CourseSubjects["Geography"] = "Geography";
    SubCategory_CourseSubjects["Economics"] = "Economics";
    SubCategory_CourseSubjects["PoliticalScience"] = "Political Science";
    SubCategory_CourseSubjects["Psychology"] = "Psychology";
    SubCategory_CourseSubjects["Philosophy"] = "Philosophy";
    SubCategory_CourseSubjects["Sociology"] = "Sociology";
    SubCategory_CourseSubjects["Business"] = "Business";
    SubCategory_CourseSubjects["Art"] = "Art";
    SubCategory_CourseSubjects["Music"] = "Music";
})(SubCategory_CourseSubjects || (exports.SubCategory_CourseSubjects = SubCategory_CourseSubjects = {}));
var SubCategory_Law;
(function (SubCategory_Law) {
    SubCategory_Law["CriminalLaw"] = "Criminal Law";
    SubCategory_Law["CivilLaw"] = "Civil Law";
    SubCategory_Law["ConstitutionalLaw"] = "Constitutional Law";
    SubCategory_Law["CorporateLaw"] = "Corporate Law";
    SubCategory_Law["InternationalLaw"] = "International Law";
    SubCategory_Law["IntellectualProperty"] = "Intellectual Property";
    SubCategory_Law["ContractLaw"] = "Contract Law";
    SubCategory_Law["FamilyLaw"] = "Family Law";
    SubCategory_Law["TaxLaw"] = "Tax Law";
    SubCategory_Law["EnvironmentalLaw"] = "Environmental Law";
})(SubCategory_Law || (exports.SubCategory_Law = SubCategory_Law = {}));
var SubCategory_Medical;
(function (SubCategory_Medical) {
    SubCategory_Medical["Anatomy"] = "Anatomy";
    SubCategory_Medical["Physiology"] = "Physiology";
    SubCategory_Medical["Pathology"] = "Pathology";
    SubCategory_Medical["Pharmacology"] = "Pharmacology";
    SubCategory_Medical["Surgery"] = "Surgery";
    SubCategory_Medical["Psychiatry"] = "Psychiatry";
    SubCategory_Medical["Pediatrics"] = "Pediatrics";
    SubCategory_Medical["Radiology"] = "Radiology";
    SubCategory_Medical["Nursing"] = "Nursing";
    SubCategory_Medical["EmergencyMedicine"] = "Emergency Medicine";
})(SubCategory_Medical || (exports.SubCategory_Medical = SubCategory_Medical = {}));
var SubCategory_Military;
(function (SubCategory_Military) {
    SubCategory_Military["Strategy"] = "Strategy";
    SubCategory_Military["Tactics"] = "Tactics";
    SubCategory_Military["Weapons"] = "Weapons";
    SubCategory_Military["Logistics"] = "Logistics";
    SubCategory_Military["Intelligence"] = "Intelligence";
    SubCategory_Military["NavalWarfare"] = "Naval Warfare";
    SubCategory_Military["AirForce"] = "Air Force";
    SubCategory_Military["SpecialForces"] = "Special Forces";
    SubCategory_Military["MilitaryHistory"] = "Military History";
    SubCategory_Military["CyberWarfare"] = "Cyber Warfare";
})(SubCategory_Military || (exports.SubCategory_Military = SubCategory_Military = {}));
var SubCategory_Language;
(function (SubCategory_Language) {
    SubCategory_Language["Afrikaans"] = "Afrikaans";
    SubCategory_Language["Albanian"] = "Albanian";
    SubCategory_Language["Amharic"] = "Amharic";
    SubCategory_Language["Arabic"] = "Arabic";
    SubCategory_Language["Armenian"] = "Armenian";
    SubCategory_Language["Assamese"] = "Assamese";
    SubCategory_Language["Azerbaijani"] = "Azerbaijani";
    SubCategory_Language["Basque"] = "Basque";
    SubCategory_Language["Belarusian"] = "Belarusian";
    SubCategory_Language["Bengali"] = "Bengali";
    SubCategory_Language["Bosnian"] = "Bosnian";
    SubCategory_Language["Bulgarian"] = "Bulgarian";
    SubCategory_Language["Burmese"] = "Burmese";
    SubCategory_Language["Catalan"] = "Catalan";
    SubCategory_Language["Cebuano"] = "Cebuano";
    SubCategory_Language["Chichewa"] = "Chichewa";
    SubCategory_Language["Chinese_Simplified"] = "Chinese (Simplified)";
    SubCategory_Language["Chinese_Traditional"] = "Chinese (Traditional)";
    SubCategory_Language["Corsican"] = "Corsican";
    SubCategory_Language["Croatian"] = "Croatian";
    SubCategory_Language["Czech"] = "Czech";
    SubCategory_Language["Danish"] = "Danish";
    SubCategory_Language["Dhivehi"] = "Dhivehi";
    SubCategory_Language["Dutch"] = "Dutch";
    SubCategory_Language["English"] = "English";
    SubCategory_Language["Esperanto"] = "Esperanto";
    SubCategory_Language["Estonian"] = "Estonian";
    SubCategory_Language["Ewe"] = "Ewe";
    SubCategory_Language["Filipino"] = "Filipino (Tagalog)";
    SubCategory_Language["Finnish"] = "Finnish";
    SubCategory_Language["French"] = "French";
    SubCategory_Language["Frisian"] = "Frisian";
    SubCategory_Language["Galician"] = "Galician";
    SubCategory_Language["Georgian"] = "Georgian";
    SubCategory_Language["German"] = "German";
    SubCategory_Language["Greek"] = "Greek";
    SubCategory_Language["Gujarati"] = "Gujarati";
    SubCategory_Language["Haitian_Creole"] = "Haitian Creole";
    SubCategory_Language["Hausa"] = "Hausa";
    SubCategory_Language["Hawaiian"] = "Hawaiian";
    SubCategory_Language["Hebrew"] = "Hebrew";
    SubCategory_Language["Hindi"] = "Hindi";
    SubCategory_Language["Hmong"] = "Hmong";
    SubCategory_Language["Hungarian"] = "Hungarian";
    SubCategory_Language["Icelandic"] = "Icelandic";
    SubCategory_Language["Igbo"] = "Igbo";
    SubCategory_Language["Indonesian"] = "Indonesian";
    SubCategory_Language["Irish"] = "Irish";
    SubCategory_Language["Italian"] = "Italian";
    SubCategory_Language["Japanese"] = "Japanese";
    SubCategory_Language["Javanese"] = "Javanese";
    SubCategory_Language["Kannada"] = "Kannada";
    SubCategory_Language["Kazakh"] = "Kazakh";
    SubCategory_Language["Khmer"] = "Khmer";
    SubCategory_Language["Kinyarwanda"] = "Kinyarwanda";
    SubCategory_Language["Korean"] = "Korean";
    SubCategory_Language["Kurdish_Kurmanji"] = "Kurdish (Kurmanji)";
    SubCategory_Language["Kyrgyz"] = "Kyrgyz";
    SubCategory_Language["Lao"] = "Lao";
    SubCategory_Language["Latin"] = "Latin";
    SubCategory_Language["Latvian"] = "Latvian";
    SubCategory_Language["Lithuanian"] = "Lithuanian";
    SubCategory_Language["Luxembourgish"] = "Luxembourgish";
    SubCategory_Language["Macedonian"] = "Macedonian";
    SubCategory_Language["Malagasy"] = "Malagasy";
    SubCategory_Language["Malay"] = "Malay";
    SubCategory_Language["Malayalam"] = "Malayalam";
    SubCategory_Language["Maltese"] = "Maltese";
    SubCategory_Language["Maori"] = "Maori";
    SubCategory_Language["Marathi"] = "Marathi";
    SubCategory_Language["Mongolian"] = "Mongolian";
    SubCategory_Language["Nepali"] = "Nepali";
    SubCategory_Language["Norwegian"] = "Norwegian";
    SubCategory_Language["Odia"] = "Odia (Oriya)";
    SubCategory_Language["Pashto"] = "Pashto";
    SubCategory_Language["Persian"] = "Persian";
    SubCategory_Language["Polish"] = "Polish";
    SubCategory_Language["Portuguese"] = "Portuguese";
    SubCategory_Language["Punjabi"] = "Punjabi";
    SubCategory_Language["Quechua"] = "Quechua";
    SubCategory_Language["Romanian"] = "Romanian";
    SubCategory_Language["Russian"] = "Russian";
    SubCategory_Language["Samoan"] = "Samoan";
    SubCategory_Language["Sanskrit"] = "Sanskrit";
    SubCategory_Language["Scottish_Gaelic"] = "Scottish Gaelic";
    SubCategory_Language["Serbian"] = "Serbian";
    SubCategory_Language["Sesotho"] = "Sesotho";
    SubCategory_Language["Shona"] = "Shona";
    SubCategory_Language["Sindhi"] = "Sindhi";
    SubCategory_Language["Sinhala"] = "Sinhala";
    SubCategory_Language["Slovak"] = "Slovak";
    SubCategory_Language["Slovenian"] = "Slovenian";
    SubCategory_Language["Somali"] = "Somali";
    SubCategory_Language["Spanish"] = "Spanish";
    SubCategory_Language["Sundanese"] = "Sundanese";
    SubCategory_Language["Swahili"] = "Swahili";
    SubCategory_Language["Swedish"] = "Swedish";
    SubCategory_Language["Tajik"] = "Tajik";
    SubCategory_Language["Tamil"] = "Tamil";
    SubCategory_Language["Tatar"] = "Tatar";
    SubCategory_Language["Telugu"] = "Telugu";
    SubCategory_Language["Thai"] = "Thai";
    SubCategory_Language["Tigrinya"] = "Tigrinya";
    SubCategory_Language["Turkish"] = "Turkish";
    SubCategory_Language["Turkmen"] = "Turkmen";
    SubCategory_Language["Ukrainian"] = "Ukrainian";
    SubCategory_Language["Urdu"] = "Urdu";
    SubCategory_Language["Uzbek"] = "Uzbek";
    SubCategory_Language["Vietnamese"] = "Vietnamese";
    SubCategory_Language["Welsh"] = "Welsh";
    SubCategory_Language["Xhosa"] = "Xhosa";
    SubCategory_Language["Yiddish"] = "Yiddish";
    SubCategory_Language["Yoruba"] = "Yoruba";
    SubCategory_Language["Zulu"] = "Zulu";
})(SubCategory_Language || (exports.SubCategory_Language = SubCategory_Language = {}));
